/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leulinsonlinepharmacyui;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import DBpart.Model;

/**
 *
 * @author eulinle_sd2022
 */
public class AddMedicine extends javax.swing.JFrame {

    /**
     * Creates new form addMed
     */
    public AddMedicine() {
        initComponents();
        this.setTitle("Add Medicine");
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addmedPanel = new javax.swing.JPanel();
        headPanel = new javax.swing.JPanel();
        addMedLabel = new javax.swing.JLabel();
        fiilText = new javax.swing.JLabel();
        brandlabel = new javax.swing.JLabel();
        genLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        brandname = new javax.swing.JTextField();
        genname = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        pharmaback = new javax.swing.JButton();
        comboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addmedPanel.setBackground(new java.awt.Color(0, 153, 153));

        headPanel.setBackground(new java.awt.Color(153, 153, 153));

        addMedLabel.setBackground(new java.awt.Color(0, 102, 102));
        addMedLabel.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        addMedLabel.setForeground(new java.awt.Color(0, 102, 102));
        addMedLabel.setText("Add Medicine");

        javax.swing.GroupLayout headPanelLayout = new javax.swing.GroupLayout(headPanel);
        headPanel.setLayout(headPanelLayout);
        headPanelLayout.setHorizontalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(addMedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(147, 147, 147))
        );
        headPanelLayout.setVerticalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(addMedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        fiilText.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        fiilText.setForeground(new java.awt.Color(153, 0, 0));
        fiilText.setText("Please fill the following:");

        brandlabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        brandlabel.setText("Enter Brand Name:");

        genLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        genLabel.setText("Enter Generic Name:");

        priceLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        priceLabel.setText("Enter Price:");

        quantityLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        quantityLabel.setText("Enter Quantity:");

        submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit.setText("Submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        pharmaback.setBackground(new java.awt.Color(153, 153, 153));
        pharmaback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pharmaback.setForeground(new java.awt.Color(0, 153, 153));
        pharmaback.setText("< Back");
        pharmaback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmabackActionPerformed(evt);
            }
        });

        comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cough", "Body Pain", "Headache", "Allergies" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addmedPanelLayout = new javax.swing.GroupLayout(addmedPanel);
        addmedPanel.setLayout(addmedPanelLayout);
        addmedPanelLayout.setHorizontalGroup(
            addmedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(addmedPanelLayout.createSequentialGroup()
                .addGroup(addmedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addmedPanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(addmedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addmedPanelLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addmedPanelLayout.createSequentialGroup()
                                .addComponent(priceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addmedPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(addmedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addmedPanelLayout.createSequentialGroup()
                                        .addComponent(brandlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(brandname, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addmedPanelLayout.createSequentialGroup()
                                        .addComponent(quantityLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addmedPanelLayout.createSequentialGroup()
                                        .addComponent(genLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(genname, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(addmedPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pharmaback))
                    .addGroup(addmedPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(fiilText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addmedPanelLayout.setVerticalGroup(
            addmedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addmedPanelLayout.createSequentialGroup()
                .addComponent(headPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pharmaback)
                .addGap(53, 53, 53)
                .addComponent(fiilText)
                .addGap(40, 40, 40)
                .addGroup(addmedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandlabel)
                    .addComponent(brandname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addmedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genLabel)
                    .addComponent(genname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(addmedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(addmedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addmedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addmedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
//        Model mod = new Model();
        String brand = brandname.getText();
        String gen = genname.getText();
        String a = "Allergies";
        String b = "Headache";
        String c = "Body Pain";
        String d = "Cough";
        String quant = quantity.getText();
        String prc = price.getText();
        String dropDownValue = (String) comboBox.getSelectedItem();
        String typ = dropDownValue;
        
        int qty = Integer.parseInt(quant);
        double price = Double.parseDouble(prc);
        
        String sql1 = "INSERT INTO `medicineforallergies` (`brandname`, `genericname`, `type`, `quantity`, `price`) VALUES ('" + brand + "', '" + gen + "', '" + typ + "', " + qty + ", " + price + ")";
        String sql2 = "INSERT INTO `medicineforheadache` (`brandname`, `genericname`, `type`, `quantity`, `price`) VALUES ('" + brand + "', '" + gen + "', '" + typ + "', " + qty + ", " + price + ")";
        String sql3 = "INSERT INTO `medicineforbodypain` (`brandname`, `genericname`, `type`, `quantity`, `price`) VALUES ('" + brand + "', '" + gen + "', '" + typ + "', " + qty + ", " + price + ")";
        String sql4 = "INSERT INTO `medicineforcough` (`brandname`, `genericname`, `type`, `quantity`, `price`) VALUES ('" + brand + "', '" + gen + "', '" + typ + "', " + qty + ", " + price + ")";

//        JOptionPane.showMessageDialog(rootPane,dropDownValue);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/eulin", "root", "");
            Statement stmt = con.createStatement();

            if (typ.equals(a) == true) {
                stmt.executeUpdate(sql1);
                JOptionPane.showMessageDialog(rootPane, "Medicine added successfully!");
                this.dispose();
                new PharmaDashboard().setVisible(true);
            } else if (typ.equals(b) == true) {
                stmt.executeUpdate(sql2);
                JOptionPane.showMessageDialog(rootPane, "Medicine added successfully!");
                this.dispose();
                new PharmaDashboard().setVisible(true);
            } else if (typ.equals(c) == true) {
                stmt.executeUpdate(sql3);
                JOptionPane.showMessageDialog(rootPane, "Medicine added successfully!");
                this.dispose();
                new PharmaDashboard().setVisible(true);
            } else if (typ.equals(d) == true) {
                stmt.executeUpdate(sql4);
                JOptionPane.showMessageDialog(rootPane, "Medicine added successfully!");
                this.dispose();
                new PharmaDashboard().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, typ);
            }
            con.close();
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Error connecting to database!");
        }
    }//GEN-LAST:event_submitMouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

    }//GEN-LAST:event_submitActionPerformed

    private void pharmabackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmabackActionPerformed
        this.setVisible(false);
        new PharmaDashboard().setVisible(true);
    }//GEN-LAST:event_pharmabackActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
//        String value = comboBox.getSelectedItem().toString();
//
//        try {
//            Class.forName("com.mysql.jdbc.Driver");
//                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/eulin", "root", "");
//                Statement stmt = con.createStatement();
//                ResultSet rs = stmt.executeQuery("SELECT * FROM `" + value + "`");
//                
//                
//
//        } catch () {
//        }
    }//GEN-LAST:event_comboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addMedLabel;
    private javax.swing.JPanel addmedPanel;
    private javax.swing.JLabel brandlabel;
    private javax.swing.JTextField brandname;
    private javax.swing.JComboBox comboBox;
    private javax.swing.JLabel fiilText;
    private javax.swing.JLabel genLabel;
    private javax.swing.JTextField genname;
    private javax.swing.JPanel headPanel;
    private javax.swing.JButton pharmaback;
    private javax.swing.JTextField price;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField quantity;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
