    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package leulinsonlinepharmacyui;

import javax.swing.JFrame;
import Controller.Controller;

/**
 *
 * @author eulinle_sd2022
 */
public class Purchase extends javax.swing.JFrame {

    /**
     * Creates new form Purchase
     */
    String uname;
    
    public Purchase() {
        initComponents();
        this.setTitle("Purchase");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public Purchase(String username) {
        initComponents();
        this.setTitle("Purchase");
        uname = username;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coughbtn = new javax.swing.JButton();
        purchasePanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        enterLabel = new javax.swing.JLabel();
        brandname = new javax.swing.JTextField();
        quantLabel = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        purchasebtn = new javax.swing.JToggleButton();
        moneyLabel = new javax.swing.JLabel();
        money = new javax.swing.JTextField();
        clicktoview = new javax.swing.JButton();

        coughbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        coughbtn.setText("Medicine for Cough");
        coughbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coughbtnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        purchasePanel.setBackground(new java.awt.Color(0, 153, 153));
        purchasePanel.setBorder(new javax.swing.border.MatteBorder(null));
        purchasePanel.setPreferredSize(new java.awt.Dimension(485, 545));

        headerPanel.setBackground(new java.awt.Color(153, 153, 153));
        headerPanel.setPreferredSize(new java.awt.Dimension(307, 88));

        headerLabel.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(0, 102, 102));
        headerLabel.setText("Purchase");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(headerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(headerLabel)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        backBTN.setBackground(new java.awt.Color(153, 153, 153));
        backBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBTN.setForeground(new java.awt.Color(0, 153, 153));
        backBTN.setText("< Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        enterLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        enterLabel.setText("Enter medicine brand name  you want to purchase:");

        brandname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandnameActionPerformed(evt);
            }
        });

        quantLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        quantLabel.setText("Enter Quantity:");

        purchasebtn.setText("Purchase");
        purchasebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchasebtnMouseClicked(evt);
            }
        });

        moneyLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        moneyLabel.setText("Enter Money:");

        clicktoview.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clicktoview.setText("Click here to view medicines");
        clicktoview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicktoviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout purchasePanelLayout = new javax.swing.GroupLayout(purchasePanel);
        purchasePanel.setLayout(purchasePanelLayout);
        purchasePanelLayout.setHorizontalGroup(
            purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
            .addGroup(purchasePanelLayout.createSequentialGroup()
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purchasePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBTN))
                    .addGroup(purchasePanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(brandname, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(purchasePanelLayout.createSequentialGroup()
                                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(quantLabel)
                                    .addComponent(moneyLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(purchasePanelLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(clicktoview, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(purchasePanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(enterLabel))
                    .addGroup(purchasePanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(purchasebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        purchasePanelLayout.setVerticalGroup(
            purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasePanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBTN)
                .addGap(29, 29, 29)
                .addComponent(clicktoview, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(enterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(brandname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantLabel)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneyLabel)
                    .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(purchasebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purchasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(purchasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        this.setVisible(false);
        new CustomerDashboard().setVisible(true);
    }//GEN-LAST:event_backBTNActionPerformed

    private void brandnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandnameActionPerformed

    private void coughbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coughbtnActionPerformed

    }//GEN-LAST:event_coughbtnActionPerformed

    private void purchasebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchasebtnMouseClicked
        String bname = brandname.getText();
        String qty = quantity.getText();
        String cash = money.getText();
        
        Controller control = new Controller();
        if(control.purchase(uname, bname, qty, cash) == true){
            this.dispose();
            CustomerDashboard dash = new CustomerDashboard(uname);
            dash.setVisible(true);
        }
        
    }//GEN-LAST:event_purchasebtnMouseClicked

    private void clicktoviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicktoviewActionPerformed
         new CustomerViewMedicine().setVisible(true);
    }//GEN-LAST:event_clicktoviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JTextField brandname;
    private javax.swing.JButton clicktoview;
    private javax.swing.JButton coughbtn;
    private javax.swing.JLabel enterLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTextField money;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JPanel purchasePanel;
    private javax.swing.JToggleButton purchasebtn;
    private javax.swing.JLabel quantLabel;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
